[package]
name = "i3_status_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
battery = "0.7.8"
chrono = "0.4.23"
i3ipc = "0.10.1"
sysinfo = "0.27.7"
